package cn.alphabets.light.config;

import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.List;

/**
 * Generated by the Light platform.
 * Do not manually modify the code.
 */
public class Configuration {
    public final App app = new App();

    public final Ignore ignore = new Ignore();

    public final Cache cache = new Cache();

    public final Push push = new Push();

    public final Wechat wechat = new Wechat();

    public final Zabbix zabbix = new Zabbix();

    public final I18n i18n = new I18n();

    public final Oracle oracle = new Oracle();

    public final Light light = new Light();

    public final Mail mail = new Mail();

    public final Db db = new Db();

    public final Salt salt = new Salt();

    public final Mq mq = new Mq();

    public final Watch watch = new Watch();

    public final Mysql mysql = new Mysql();

    public static final class App {
        public final String getViews() {
            return "views";
        }

        public final String getStatic() {
            return "/static";
        }

        public final String getCookieSecret() {
            return "light";
        }

        public final String getSessionSecret() {
            return "light";
        }

        public final String getSessionKey() {
            return "light.sid";
        }

        public final String getTmp() {
            return "/tmp";
        }

        public final String getHmackey() {
            return "light";
        }

        public final Long getSessionTimeout() {
            return 168L;
        }

        public final Long getSessionTimeoutMobile() {
            return 720L;
        }

        public final String getStamp() {
            return "453fc7f3";
        }

        public final String getRestApiPrefix() {
            return "";
        }

        public final String getWebsite() {
            return "http://light.starwall.org";
        }

        public final String getHome() {
            return "/login";
        }

        public final Long getTimeout() {
            return 30L;
        }

        public final String getHost() {
            return "localhost";
        }

        public final String getDomain() {
            return "LightDB";
        }

        public final String getError() {
            return "/error";
        }

        public final String getVersion() {
            return "v0.0.1";
        }

        public final String getSecret() {
            return "light";
        }

        public final String getProfileKey() {
            return "light.profile";
        }

        public final String getCommonDomain() {
            return ".starwall.org";
        }

        public final String getTokenSecret() {
            return "1b3bd5b82c8ded62d85da744b2beefa8";
        }

        public final Long getTokenExpires() {
            return 86400L;
        }

        public final String getProxy() {
            return "http://proxy:3128";
        }
    }

    public static final class Cache {
        public final Boolean getEnable() {
            return true;
        }

        public final String getType() {
            return "memory";
        }

        public final Long getMax() {
            return 500L;
        }

        public final Long getMaxAge() {
            return 43200L;
        }
    }

    public static final class Zabbix {
        public final String getUser() {
            return "Admin";
        }

        public final String getPass() {
            return "zabbix";
        }

        public final String getHost() {
            return "zabbix.starwall.org";
        }
    }

    public static final class Oracle {
        public final Boolean getEnable() {
            return false;
        }

        public final String getHost() {
            return "oracle";
        }

        public final Long getPort() {
            return 1521L;
        }

        public final String getDbname() {
            return "light";
        }

        public final String getUser() {
            return "system";
        }

        public final String getPass() {
            return "manager";
        }

        public final Long getPool() {
            return 3L;
        }
    }

    public static final class Salt {
        public final String getPass() {
            return "alphabets";
        }
    }

    public static final class Mail {
        public final Auth auth = new Auth();

        public final String getService() {
            return "QQex";
        }
    }

    public static final class Mq {
        public final String getHost() {
            return "mq.alphabets.cn";
        }

        public final Long getPort() {
            return 54017L;
        }

        public final String getLogin() {
            return "root";
        }

        public final String getPassword() {
            return "alphabets";
        }
    }

    public static final class Auth {
        public final String getUser() {
            return "light.support@alphabets.cn";
        }

        public final String getPass() {
            return "alphabets@2014";
        }
    }

    public static final class Logdb {
        public final String getUser() {
            return "log";
        }

        public final String getPass() {
            return "1234";
        }
    }

    public static final class Wechat {
        public final Open open = new Open();

        public final String getToken() {
            return "light";
        }

        public final String getEncodingAESKey() {
            return "FIb9ifFZpd8GJlBfdOq7Ois2OMFgWTo4AIf7yoLgLAe";
        }

        public final String getCorpID() {
            return "wx17cb32991794a206";
        }

        public final String getSecret() {
            return "n1d8Cvwr6D4rUtaFyBcg-H0-92rx7hs0ZlMwBUZGwSojnf8SRRwmJeuI-Xn7ctOs";
        }

        public final Long getAgentId() {
            return 2L;
        }
    }

    public static final class Admin {
        public final String getUser() {
            return "light";
        }

        public final String getPass() {
            return "2e35501c2b7e";
        }
    }

    public static final class Sample {
        public final String getUser() {
            return "sample";
        }

        public final String getPass() {
            return "1234";
        }
    }

    public static final class Push {
        public final String getGetuiAppId() {
            return "";
        }

        public final String getGetuiAppKey() {
            return "";
        }

        public final String getGetuiMasterSecrt() {
            return "";
        }

        public final Boolean getApnDevelopment() {
            return true;
        }

        public final String getApnCertDevelopment() {
            return "aps_development.pem";
        }

        public final String getApnCertProduction() {
            return "aps_production.pem";
        }

        public final String getApnKey() {
            return "aps_key.pem";
        }

        public final Boolean getSocketEnable() {
            return true;
        }

        public final String getSocketServer() {
            return "socket.starwall.org";
        }

        public final Long getSocketPort() {
            return 56017L;
        }

        public final String getSocketProtocol() {
            return "ws";
        }

        public final String getBaiduSecretKey() {
            return "Euhgo6z9SWm3Z3YTQrPhlF9L3F0UQTU7";
        }

        public final String getBaiduApiKey() {
            return "4tik7VTn75wkKG1cC1nvRnQn";
        }
    }

    public static final class I18n {
        public final String getCache() {
            return "memory";
        }

        public final String getDefaultLang() {
            return "zh";
        }

        public final List<String> getLangs() {
            return java.util.Arrays.asList("zh");
        }

        public final String getCategory() {
            return "light";
        }
    }

    public static final class Site {
        public final String getUser() {
            return "site";
        }

        public final String getPass() {
            return "1234";
        }
    }

    public static final class Light {
        public final Gitlab gitlab = new Gitlab();

        public final List<String> getServertype() {
            return java.util.Arrays.asList("Master",
                    "Admin",
                    "Application",
                    "Database",
                    "LoadBalance",
                    "DNS");
        }

        public final String getRepository() {
            return "http://root:alphabets@git.alphabets.cn";
        }

        public final String getDns() {
            return "10.163.170.150";
        }

        public final String getDomain() {
            return "light.starwall.org";
        }

        public final String getMaster() {
            return "salt.starwall.org";
        }

        public final String getMongo() {
            return "db.alphabets.cn";
        }

        public final String getDatacenter() {
            return "UCloud";
        }
    }

    public static final class Watch {
        public final String getBi() {
            return "<script type='text/javascript'>window.BWEUM||(BWEUM={});BWEUM.info = {\"stand\":true,\"agentType\":\"browser\",\"agent\":\"bi-collector.oneapm.com/static/js/bw-send-411.4.5.js\",\"beaconUrl\":\"bi-collector.oneapm.com/beacon\",\"licenseKey\":\"JfYEy~eUIfjMu2iy\",\"applicationID\":2273083};</script><script type=\"text/javascript\" src=\"//bi-collector.oneapm.com/static/js/bw-loader-411.4.5.js\"></script>";
        }
    }

    public static final class Root {
        public final String getPass() {
            return "e37cc2ba9de7";
        }

        public final String getUser() {
            return "root";
        }
    }

    public static final class Ignore {
        public final List<String> getAuth() {
            return java.util.Arrays.asList("^/stylesheets",
                    "^/javascripts",
                    "^/images",
                    "^/bower",
                    "^/unify",
                    "^/account/*",
                    "^/login",
                    "^/api/account/login.*",
                    "^/api/developer/*",
                    "^/api/account/register.*",
                    "^/api/account/verify.*",
                    "^/api/account/captcha.*",
                    "^/api/account/forget.*",
                    "^/api/account/resetpwd.*",
                    "^/api/account/accessToken.*",
                    "^/api/account/sso.*",
                    "^/api/feedback/add.*",
                    "^/api/document/markdown.*",
                    "^/api/system/signal*",
                    "^/paper/.*",
                    "^/api/form/get.*",
                    "^/api/wechat/wechatlogin",
                    "^/markdown/.*");
        }

        public final List<String> getTimeout() {
            return java.util.Arrays.asList("^/api/file/upload*",
                    "^/api/file/add*",
                    "^/api/file/update*",
                    "^/api/middleware/* 120",
                    "^/api/code/init 180",
                    "^/api/app/* 90");
        }

        public final List<String> getCsrf() {
            return new java.util.ArrayList<>();
        }

        public final List<String> getPolicy() {
            return java.util.Arrays.asList("^/api/file/image*");
        }
    }

    public static final class Gitlab {
        public final String getOuter() {
            return "git.alphabets.cn";
        }

        public final String getInner() {
            return "git.alphabets.cn";
        }

        public final String getUser() {
            return "root";
        }

        public final String getPass() {
            return "alphabets";
        }

        public final String getUrl() {
            return "git.alphabets.cn";
        }
    }

    public static final class Mysql {
        public final String getDbname() {
            return "light";
        }

        public final Boolean getEnable() {
            return true;
        }

        public final String getHost() {
            return "db2";
        }

        public final String getPass() {
            return "iB0!ec9Y";
        }

        public final Long getPool() {
            return 5L;
        }

        public final String getPort() {
            return "3306";
        }

        public final String getUser() {
            return "admin";
        }
    }

    public static final class Db {
        public final Logdb logdb = new Logdb();

        public final Sample sample = new Sample();

        public final Site site = new Site();

        public final Admin admin = new Admin();

        public final Root root = new Root();
    }

    public static final class Open {
        public final String getAppID() {
            return "wx7d0e730b3c85d354";
        }

        public final String getAppSecret() {
            return "9f3e234fb1aa42ad34eee75a6c02f4c5";
        }
    }
}

