- _id: 55530a8a522b337520746ef4
  description: cookie secret
  displayType: 0
  key: cookieSecret
  options: []
  type: app
  value: light
  valueType: string
  version: 0.5.8
- _id: 55530a8a522b337520746ef8
  description: sha256加密用key字符串
  displayType: 0
  key: hmackey
  options: []
  type: app
  value: light
  valueType: string
  version: 0.5.8
- _id: 5554b1a37e719466a6419d2c
  description: 主页
  displayType: 0
  key: home
  options: []
  type: app
  value: /login.html
  valueType: string
  version: 0.5.8
- _id: 55530a8a522b337520746ef6
  description: express的session key
  displayType: 0
  key: sessionKey
  options: []
  type: app
  value: light.sid
  valueType: string
  version: 0.5.8
- _id: 55530a8a522b337520746ef5
  description: express的session secret
  displayType: 0
  key: sessionSecret
  options: []
  type: app
  value: light
  valueType: string
  version: 0.5.8
- _id: 55530a8a522b337520746efa
  description: Session超时时间，小时（24 * 7 一周）
  displayType: 0
  key: sessionTimeout
  options: []
  type: app
  value: '168'
  valueType: number
  version: 0.5.8
- _id: 55530a8a522b337520746efb
  description: Session超时时间，小时（24 * 30 一个月）移动端
  displayType: 0
  key: sessionTimeoutMobile
  options: []
  type: app
  value: '720'
  valueType: number
  version: 0.5.8
- _id: 55530a8a522b337520746efc
  description: 让浏览器缓存失效的静态资源后缀
  displayType: 0
  key: stamp
  options: []
  type: app
  value: 453fc7f5
  valueType: string
  version: 0.5.8
- _id: 55530a8a522b337520746ef3
  description: 静态文件的存放位置
  displayType: 0
  key: static
  options: []
  type: app
  value: /static
  valueType: string
  version: 0.5.8
- _id: 556473511d8a66e61e348d27
  description: 请求超时(秒)
  displayType: 0
  key: timeout
  options: []
  type: app
  value: '30'
  valueType: number
  version: 0.5.8
- _id: 55530a8a522b337520746ef7
  description: 保存临时文件用路径（如上传文件等）
  displayType: 0
  key: tmp
  options: []
  type: app
  value: /tmp
  valueType: string
  version: 0.5.8
- _id: 561e76c85d52306d58477e6f
  description: token有效期限
  displayType: 0
  key: tokenExpires
  options: []
  type: app
  value: '86400'
  valueType: number
  version: 0.5.8
- _id: 561e71284936762157a98036
  description: JWT token用key
  displayType: 0
  key: tokenSecret
  options: []
  type: app
  value: 1b3bd5b82c8ded62d85da744b2beefa8
  valueType: string
  version: 0.5.8
- _id: 557f890acce00e65dddddc06
  description: 应用版本
  displayType: 0
  key: version
  options: []
  type: app
  value: 0.5.8
  valueType: string
  version: 0.5.8
- _id: 55530a8a522b337520746ef1
  description: ejs的模板存放位置，应用程序需要根据实际路径进行设定
  displayType: 0
  key: views
  options: []
  type: app
  value: views
  valueType: string
  version: 0.5.8
- _id: 55ab6d0b0b669c0500bb2c85
  description: ''
  displayType: 4
  key: admin.pass
  options: []
  type: db
  value: 2e35501c2b7e
  valueType: string
  version: 0.5.8
- _id: 55ab6cad0b669c0500bb2c84
  description: ''
  displayType: 0
  key: admin.user
  options: []
  type: db
  value: light
  valueType: string
  version: 0.5.8
- _id: 55ab6d4a68f1cd05000aabca
  description: ''
  displayType: 4
  key: root.pass
  options: []
  type: db
  value: e37cc2ba9de7
  valueType: string
  version: 0.5.8
- _id: 55ab6d5b0b669c0500bb2c86
  description: ''
  displayType: 0
  key: root.user
  options: []
  type: db
  value: root
  valueType: string
  version: 0.5.8
- _id: 57e6683289935b05008e5ee5
  description: docker 镜像编译服务器地址
  displayType: 0
  key: builder
  options: []
  type: docker
  value: 'tcp://172.16.10.186:3375'
  valueType: string
  version: 0.5.8
- _id: 57e66c7852cdd90500d6e2b2
  description: docker 镜像编译服务器地址（开发环境用）
  displayType: 0
  key: builderdev
  options: []
  type: docker
  value: 'tcp://120.27.14.148:3375'
  valueType: string
  version: 0.5.8
- _id: 586894e6417c420005f538e3
  description: 日志服务器
  displayType: 0
  key: log
  options: []
  type: docker
  value: '172.16.10.186:24224'
  valueType: string
  version: 0.5.8
- _id: 5948c17efc0ea5156250c41a
  description: Docker Swarm Manager服务器
  displayType: 0
  key: manager
  options: []
  type: docker
  value: 'tcp://172.16.10.182:3375'
  valueType: string
  version: 0.5.8
- _id: 5948c1c3fc0ea5156250c41b
  description: Docker Swarm Manager服务器（开发环境用）
  displayType: 0
  key: managerdev
  options: []
  type: docker
  value: 'tcp://118.190.148.246:3375'
  valueType: string
  version: 0.5.8
- _id: 57e668fd723aea050095fd6e
  description: 是否开启代理
  displayType: 1
  key: proxy.enable
  options: []
  type: docker
  value: 'true'
  valueType: boolean
  version: 0.5.8
- _id: 57e668dfc93cfd05004e44c7
  description: 编译镜像时使用的代理服务器地址
  displayType: 0
  key: proxy.http
  options: []
  type: docker
  value: 'http://172.16.10.186:3128'
  valueType: string
  version: 0.5.8
- _id: 57e66936723aea050095fd6f
  description: 编译镜像时使用的代理服务器地址
  displayType: 0
  key: proxy.https
  options: []
  type: docker
  value: 'http://172.16.10.186:13128'
  valueType: string
  version: 0.5.8
- _id: 5553104345f3277824903e7d
  description: 无需认证即可访问的资源列表
  displayType: 3
  key: auth
  options: []
  type: ignore
  value:
    - ^/static
    - ^/login.html
    - ^/register.html
    - ^/api/account/login.*
    - ^/api/account/register.*
    - ^/api/account/captcha.*
    - ^/api/account/forget.*
    - ^/api/account/resetpwd.*
    - ^/api/account/token.*
    - ^/api/feedback/add.*
    - ^/api/document/markdown.*
    - ^/api/system/signal*
    - ^/api/form/get.*
    - ^/api/wechat/login
    - ^/document.htm.*
    - ^/api/system/version.*
  valueType: array
  version: 0.5.8
- _id: 5553104345f3277824903e7f
  description: 不校验csrf
  displayType: 3
  key: csrf
  options: []
  type: ignore
  value:
    - ^/api/account/login.*
    - ^/api/account/token.*
    - ^/api/container/run.*
    - ^/api/container/start.*
    - ^/api/container/stop.*
    - ^/api/container/remove.*
    - ^/api/container/update.*
  valueType: array
  version: 0.5.8
- _id: 567fa58e4082aa9326e623f8
  description: 调用策略检查对象外的API
  displayType: 3
  key: policy
  options: []
  type: ignore
  value:
    - ^/api/file/image*
    - ^/api/account/accessToken
    - ^/a
  valueType: array
  version: 0.5.8
- _id: 5553104345f3277824903e7e
  description: 不受超时限定的资源列表
  displayType: 3
  key: timeout
  options: []
  type: ignore
  value:
    - ^/api/file/upload*
    - ^/api/file/add*
    - ^/api/file/update*
    - ^/api/middleware/* 120
    - ^/api/code/init 180
    - ^/api/app/* 90
    - ^/api/image/* 600
    - ^/api/container/* 600
  valueType: array
  version: 0.5.8
- _id: 55bb393fefd3440500c444f6
  description: RabbitMQ地址
  displayType: 0
  key: host
  options: []
  type: mq
  value: rabbit
  valueType: string
  version: 0.5.8
- _id: 55bb39a2c1bfd30500760149
  description: RabbitMQ 账户
  displayType: 0
  key: login
  options: []
  type: mq
  value: root
  valueType: string
  version: 0.5.8
- _id: 55bb39bfefd3440500c444f7
  description: RabbitMQ 密码
  displayType: 4
  key: password
  options: []
  type: mq
  value: alphabets
  valueType: string
  version: 0.5.8
- _id: 55bb397fc1bfd30500760142
  description: RabbitMQ 端口
  displayType: 0
  key: port
  options: []
  type: mq
  value: '5672'
  valueType: number
  version: 0.5.8
- _id: 56ea6cec3e2a7e0600f27dca
  description: 微信开放平台应用ID
  displayType: 0
  key: open.appID
  options: []
  type: wechat
  value: wx7d0e730b3c85d354
  valueType: string
  version: 0.5.8
- _id: 56ea6cb5ecc8ed0500fc9c98
  description: ''
  displayType: 0
  key: open.appSecret
  options: []
  type: wechat
  value: 9f3e234fb1aa42ad34eee75a6c02f4c5
  valueType: string
  version: 0.5.8
- _id: 587c9325e970ce000554ca6c
  description: 小程序 AppID
  displayType: 0
  key: xcx.AppID
  options: []
  type: wechat
  value: wx0506a7d7562c486f
  valueType: string
  version: 0.5.8
- _id: 587c97dae970ce000554ca6d
  description: 小程序 AppSecret
  displayType: 0
  key: xcx.AppSecret
  options: []
  type: wechat
  value: 98b7f48e0eebb6bd3c720902560b6c25
  valueType: string
  version: 0.5.8
