package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModAuthority extends ModCommon {
  private String description;

  private String name;

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }
}
