package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;

import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModAccess extends ModCommon {
  private String resource;

  private String type;

  private String description;

  private List authes;

  public String getResource() {
    return this.resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public List getAuthes() {
    return this.authes;
  }

  public void setAuthes(List authes) {
    this.authes = authes;
  }
}
