package cn.alphabets.light.entity;

import cn.alphabets.light.model.Entity;
import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModBoard extends ModCommon {
  private String action;

  private String path;

  private List<Filters> filters;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long type;

  private List<Selects> selects;

  private List<Sorts> sorts;

  private String api;

  @JsonProperty("class")
  private String class_;

  private String description;

  private String schema;

  private String script;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long kind;

  private String version;

  private Boolean free;

  public String getAction() {
    return this.action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public String getPath() {
    return this.path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public List<Filters> getFilters() {
    return this.filters;
  }

  public void setFilters(List<Filters> filters) {
    this.filters = filters;
  }

  public Long getType() {
    return this.type;
  }

  public void setType(Long type) {
    this.type = type;
  }

  public List<Selects> getSelects() {
    return this.selects;
  }

  public void setSelects(List<Selects> selects) {
    this.selects = selects;
  }

  public List<Sorts> getSorts() {
    return this.sorts;
  }

  public void setSorts(List<Sorts> sorts) {
    this.sorts = sorts;
  }

  public String getApi() {
    return this.api;
  }

  public void setApi(String api) {
    this.api = api;
  }

  public String getClass_() {
    return this.class_;
  }

  public void setClass_(String class_) {
    this.class_ = class_;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getSchema() {
    return this.schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public String getScript() {
    return this.script;
  }

  public void setScript(String script) {
    this.script = script;
  }

  public Long getKind() {
    return this.kind;
  }

  public void setKind(Long kind) {
    this.kind = kind;
  }

  public String getVersion() {
    return this.version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public Boolean getFree() {
    return this.free;
  }

  public void setFree(Boolean free) {
    this.free = free;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Filters extends Entity {
    @JsonProperty("default")
    private String default_;

    private String group;

    private String key;

    private String operator;

    private String parameter;

    private String type;

    public String getDefault_() {
      return this.default_;
    }

    public void setDefault_(String default_) {
      this.default_ = default_;
    }

    public String getGroup() {
      return this.group;
    }

    public void setGroup(String group) {
      this.group = group;
    }

    public String getKey() {
      return this.key;
    }

    public void setKey(String key) {
      this.key = key;
    }

    public String getOperator() {
      return this.operator;
    }

    public void setOperator(String operator) {
      this.operator = operator;
    }

    public String getParameter() {
      return this.parameter;
    }

    public void setParameter(String parameter) {
      this.parameter = parameter;
    }

    public String getType() {
      return this.type;
    }

    public void setType(String type) {
      this.type = type;
    }
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Selects extends Entity {
    private String key;

    private Boolean select;

    private String alias;

    private List fields;

    private String format;

    private String type;

    private Boolean readonly;

    private Boolean display;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long reserved;

    private String schema;

    private Object conditions;

    public String getKey() {
      return this.key;
    }

    public void setKey(String key) {
      this.key = key;
    }

    public Boolean getSelect() {
      return this.select;
    }

    public void setSelect(Boolean select) {
      this.select = select;
    }

    public String getAlias() {
      return this.alias;
    }

    public void setAlias(String alias) {
      this.alias = alias;
    }

    public List getFields() {
      return this.fields;
    }

    public void setFields(List fields) {
      this.fields = fields;
    }

    public String getFormat() {
      return this.format;
    }

    public void setFormat(String format) {
      this.format = format;
    }

    public String getType() {
      return this.type;
    }

    public void setType(String type) {
      this.type = type;
    }

    public Boolean getReadonly() {
      return this.readonly;
    }

    public void setReadonly(Boolean readonly) {
      this.readonly = readonly;
    }

    public Boolean getDisplay() {
      return this.display;
    }

    public void setDisplay(Boolean display) {
      this.display = display;
    }

    public Long getReserved() {
      return this.reserved;
    }

    public void setReserved(Long reserved) {
      this.reserved = reserved;
    }

    public String getSchema() {
      return this.schema;
    }

    public void setSchema(String schema) {
      this.schema = schema;
    }

    public Object getConditions() {
      return this.conditions;
    }

    public void setConditions(Object conditions) {
      this.conditions = conditions;
    }
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Sorts extends Entity {
    private String key;

    private String order;

    private String dynamic;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long index;

    public String getKey() {
      return this.key;
    }

    public void setKey(String key) {
      this.key = key;
    }

    public String getOrder() {
      return this.order;
    }

    public void setOrder(String order) {
      this.order = order;
    }

    public String getDynamic() {
      return this.dynamic;
    }

    public void setDynamic(String dynamic) {
      this.dynamic = dynamic;
    }

    public Long getIndex() {
      return this.index;
    }

    public void setIndex(Long index) {
      this.index = index;
    }
  }
}
