package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModCode extends ModCommon {
  private String app;

  private String name;

  private String source;

  private String type;

  private String md5;

  private String lang;

  public String getApp() {
    return this.app;
  }

  public void setApp(String app) {
    this.app = app;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getSource() {
    return this.source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getMd5() {
    return this.md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  public String getLang() {
    return this.lang;
  }

  public void setLang(String lang) {
    this.lang = lang;
  }
}
