package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModCounter extends ModCommon {
  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long sequence;

  public Long getSequence() {
    return this.sequence;
  }

  public void setSequence(Long sequence) {
    this.sequence = sequence;
  }
}
