package cn.alphabets.light.entity;

import cn.alphabets.light.model.Entity;
import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModEtl extends ModCommon {
  private String description;

  private String schema;

  private String type;

  private String charset;

  private String kind;

  @JsonProperty("class")
  private String class_;

  private List<Mappings> mappings;

  private String name;

  private String primitive;

  private String processed;

  private Boolean allowError;

  private Boolean allowUpdate;

  private List uniqueKey;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long allowErrorMax;

  private List<Filters> filters;

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getSchema() {
    return this.schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getCharset() {
    return this.charset;
  }

  public void setCharset(String charset) {
    this.charset = charset;
  }

  public String getKind() {
    return this.kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public String getClass_() {
    return this.class_;
  }

  public void setClass_(String class_) {
    this.class_ = class_;
  }

  public List<Mappings> getMappings() {
    return this.mappings;
  }

  public void setMappings(List<Mappings> mappings) {
    this.mappings = mappings;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getPrimitive() {
    return this.primitive;
  }

  public void setPrimitive(String primitive) {
    this.primitive = primitive;
  }

  public String getProcessed() {
    return this.processed;
  }

  public void setProcessed(String processed) {
    this.processed = processed;
  }

  public Boolean getAllowError() {
    return this.allowError;
  }

  public void setAllowError(Boolean allowError) {
    this.allowError = allowError;
  }

  public Boolean getAllowUpdate() {
    return this.allowUpdate;
  }

  public void setAllowUpdate(Boolean allowUpdate) {
    this.allowUpdate = allowUpdate;
  }

  public List getUniqueKey() {
    return this.uniqueKey;
  }

  public void setUniqueKey(List uniqueKey) {
    this.uniqueKey = uniqueKey;
  }

  public Long getAllowErrorMax() {
    return this.allowErrorMax;
  }

  public void setAllowErrorMax(Long allowErrorMax) {
    this.allowErrorMax = allowErrorMax;
  }

  public List<Filters> getFilters() {
    return this.filters;
  }

  public void setFilters(List<Filters> filters) {
    this.filters = filters;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Mappings extends Entity {
    private String key;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long col;

    private String schema;

    private Object conditions;

    private String fields;

    private Object sanitize;

    private String title;

    private String variable;

    public String getKey() {
      return this.key;
    }

    public void setKey(String key) {
      this.key = key;
    }

    public Long getCol() {
      return this.col;
    }

    public void setCol(Long col) {
      this.col = col;
    }

    public String getSchema() {
      return this.schema;
    }

    public void setSchema(String schema) {
      this.schema = schema;
    }

    public Object getConditions() {
      return this.conditions;
    }

    public void setConditions(Object conditions) {
      this.conditions = conditions;
    }

    public String getFields() {
      return this.fields;
    }

    public void setFields(String fields) {
      this.fields = fields;
    }

    public Object getSanitize() {
      return this.sanitize;
    }

    public void setSanitize(Object sanitize) {
      this.sanitize = sanitize;
    }

    public String getTitle() {
      return this.title;
    }

    public void setTitle(String title) {
      this.title = title;
    }

    public String getVariable() {
      return this.variable;
    }

    public void setVariable(String variable) {
      this.variable = variable;
    }
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Filters extends Entity {
    private String key;

    private String operator;

    private String parameter;

    public String getKey() {
      return this.key;
    }

    public void setKey(String key) {
      this.key = key;
    }

    public String getOperator() {
      return this.operator;
    }

    public void setOperator(String operator) {
      this.operator = operator;
    }

    public String getParameter() {
      return this.parameter;
    }

    public void setParameter(String parameter) {
      this.parameter = parameter;
    }
  }
}
