package cn.alphabets.light.entity;

import cn.alphabets.light.model.Entity;
import cn.alphabets.light.model.ModBase;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModForm extends ModBase {
  private String description;

  private String schema;

  private Boolean draft;

  private List<Items> items;

  private String name;

  private String type;

  private Long column;

  private String tag;

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getSchema() {
    return this.schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public Boolean getDraft() {
    return this.draft;
  }

  public void setDraft(Boolean draft) {
    this.draft = draft;
  }

  public List<Items> getItems() {
    return this.items;
  }

  public void setItems(List<Items> items) {
    this.items = items;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Long getColumn() {
    return this.column;
  }

  public void setColumn(Long column) {
    this.column = column;
  }

  public String getTag() {
    return this.tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Items extends Entity {
    private String lineColor;

    private List selectOption;

    private String selectStyle;

    private Long colSpan;

    private String description;

    private String disabled;

    private String labelColor;

    private String labelEscaped;

    private String type;

    private Object defaults;

    private String labelFont;

    private String labelSize;

    private String name;

    private String textPlaceholder;

    private Long col;

    private String labelDecoration;

    private String textIcon;

    private String textIconAppend;

    private String title;

    private Long row;

    private Long rowSpan;

    private List addition;

    private String locale;

    private Long textRows;

    private String textMin;

    private String textMax;

    private String textDateFormat;

    private String fileMultiple;

    private String fileAccept;

    private List gridTitle;

    private Boolean gridBordered;

    private Boolean gridStriped;

    private String gridTitleColor;

    private String gridTitleColorBackground;

    private String videoControls;

    private String videoAutoplay;

    private String videoType;

    private String blockIcon;

    private String blockIconOn;

    public String getLineColor() {
      return this.lineColor;
    }

    public void setLineColor(String lineColor) {
      this.lineColor = lineColor;
    }

    public List getSelectOption() {
      return this.selectOption;
    }

    public void setSelectOption(List selectOption) {
      this.selectOption = selectOption;
    }

    public String getSelectStyle() {
      return this.selectStyle;
    }

    public void setSelectStyle(String selectStyle) {
      this.selectStyle = selectStyle;
    }

    public Long getColSpan() {
      return this.colSpan;
    }

    public void setColSpan(Long colSpan) {
      this.colSpan = colSpan;
    }

    public String getDescription() {
      return this.description;
    }

    public void setDescription(String description) {
      this.description = description;
    }

    public String getDisabled() {
      return this.disabled;
    }

    public void setDisabled(String disabled) {
      this.disabled = disabled;
    }

    public String getLabelColor() {
      return this.labelColor;
    }

    public void setLabelColor(String labelColor) {
      this.labelColor = labelColor;
    }

    public String getLabelEscaped() {
      return this.labelEscaped;
    }

    public void setLabelEscaped(String labelEscaped) {
      this.labelEscaped = labelEscaped;
    }

    public String getType() {
      return this.type;
    }

    public void setType(String type) {
      this.type = type;
    }

    public Object getDefaults() {
      return this.defaults;
    }

    public void setDefaults(Object defaults) {
      this.defaults = defaults;
    }

    public String getLabelFont() {
      return this.labelFont;
    }

    public void setLabelFont(String labelFont) {
      this.labelFont = labelFont;
    }

    public String getLabelSize() {
      return this.labelSize;
    }

    public void setLabelSize(String labelSize) {
      this.labelSize = labelSize;
    }

    public String getName() {
      return this.name;
    }

    public void setName(String name) {
      this.name = name;
    }

    public String getTextPlaceholder() {
      return this.textPlaceholder;
    }

    public void setTextPlaceholder(String textPlaceholder) {
      this.textPlaceholder = textPlaceholder;
    }

    public Long getCol() {
      return this.col;
    }

    public void setCol(Long col) {
      this.col = col;
    }

    public String getLabelDecoration() {
      return this.labelDecoration;
    }

    public void setLabelDecoration(String labelDecoration) {
      this.labelDecoration = labelDecoration;
    }

    public String getTextIcon() {
      return this.textIcon;
    }

    public void setTextIcon(String textIcon) {
      this.textIcon = textIcon;
    }

    public String getTextIconAppend() {
      return this.textIconAppend;
    }

    public void setTextIconAppend(String textIconAppend) {
      this.textIconAppend = textIconAppend;
    }

    public String getTitle() {
      return this.title;
    }

    public void setTitle(String title) {
      this.title = title;
    }

    public Long getRow() {
      return this.row;
    }

    public void setRow(Long row) {
      this.row = row;
    }

    public Long getRowSpan() {
      return this.rowSpan;
    }

    public void setRowSpan(Long rowSpan) {
      this.rowSpan = rowSpan;
    }

    public List getAddition() {
      return this.addition;
    }

    public void setAddition(List addition) {
      this.addition = addition;
    }

    public String getLocale() {
      return this.locale;
    }

    public void setLocale(String locale) {
      this.locale = locale;
    }

    public Long getTextRows() {
      return this.textRows;
    }

    public void setTextRows(Long textRows) {
      this.textRows = textRows;
    }

    public String getTextMin() {
      return this.textMin;
    }

    public void setTextMin(String textMin) {
      this.textMin = textMin;
    }

    public String getTextMax() {
      return this.textMax;
    }

    public void setTextMax(String textMax) {
      this.textMax = textMax;
    }

    public String getTextDateFormat() {
      return this.textDateFormat;
    }

    public void setTextDateFormat(String textDateFormat) {
      this.textDateFormat = textDateFormat;
    }

    public String getFileMultiple() {
      return this.fileMultiple;
    }

    public void setFileMultiple(String fileMultiple) {
      this.fileMultiple = fileMultiple;
    }

    public String getFileAccept() {
      return this.fileAccept;
    }

    public void setFileAccept(String fileAccept) {
      this.fileAccept = fileAccept;
    }

    public List getGridTitle() {
      return this.gridTitle;
    }

    public void setGridTitle(List gridTitle) {
      this.gridTitle = gridTitle;
    }

    public Boolean getGridBordered() {
      return this.gridBordered;
    }

    public void setGridBordered(Boolean gridBordered) {
      this.gridBordered = gridBordered;
    }

    public Boolean getGridStriped() {
      return this.gridStriped;
    }

    public void setGridStriped(Boolean gridStriped) {
      this.gridStriped = gridStriped;
    }

    public String getGridTitleColor() {
      return this.gridTitleColor;
    }

    public void setGridTitleColor(String gridTitleColor) {
      this.gridTitleColor = gridTitleColor;
    }

    public String getGridTitleColorBackground() {
      return this.gridTitleColorBackground;
    }

    public void setGridTitleColorBackground(String gridTitleColorBackground) {
      this.gridTitleColorBackground = gridTitleColorBackground;
    }

    public String getVideoControls() {
      return this.videoControls;
    }

    public void setVideoControls(String videoControls) {
      this.videoControls = videoControls;
    }

    public String getVideoAutoplay() {
      return this.videoAutoplay;
    }

    public void setVideoAutoplay(String videoAutoplay) {
      this.videoAutoplay = videoAutoplay;
    }

    public String getVideoType() {
      return this.videoType;
    }

    public void setVideoType(String videoType) {
      this.videoType = videoType;
    }

    public String getBlockIcon() {
      return this.blockIcon;
    }

    public void setBlockIcon(String blockIcon) {
      this.blockIcon = blockIcon;
    }

    public String getBlockIconOn() {
      return this.blockIconOn;
    }

    public void setBlockIconOn(String blockIconOn) {
      this.blockIconOn = blockIconOn;
    }
  }
}
