package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModFunction extends ModCommon {
  private String order;

  private String description;

  private String menu;

  private String type;

  private String url;

  private String icon;

  private String kind;

  private String parent;

  private String version;

  private String status;

  public String getOrder() {
    return this.order;
  }

  public void setOrder(String order) {
    this.order = order;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getMenu() {
    return this.menu;
  }

  public void setMenu(String menu) {
    this.menu = menu;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getIcon() {
    return this.icon;
  }

  public void setIcon(String icon) {
    this.icon = icon;
  }

  public String getKind() {
    return this.kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public String getParent() {
    return this.parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }

  public String getVersion() {
    return this.version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }
}
