package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import cn.alphabets.light.model.deserializer.ObjectIdDeserializer;
import cn.alphabets.light.model.serializer.ObjectIdSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.lang.Long;
import java.lang.String;
import org.bson.types.ObjectId;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModFile extends ModCommon {
  private String contentType;

  @JsonDeserialize(
      using = ObjectIdDeserializer.class
  )
  @JsonSerialize(
      using = ObjectIdSerializer.class
  )
  private ObjectId fileId;

  private String path;

  private String name;

  private String type;

  private String description;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long length;

  public String getContentType() {
    return this.contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public ObjectId getFileId() {
    return this.fileId;
  }

  public void setFileId(ObjectId fileId) {
    this.fileId = fileId;
  }

  public String getPath() {
    return this.path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Long getLength() {
    return this.length;
  }

  public void setLength(Long length) {
    this.length = length;
  }
}
