package cn.alphabets.light.entity;

import cn.alphabets.light.model.Entity;
import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModForm extends ModCommon {
  private String name;

  private String description;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long column;

  private String schema;

  @JsonProperty("public")
  private Boolean public_;

  private String id;

  private String ver;

  private Boolean active;

  private String type;

  private List<Items> items;

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Long getColumn() {
    return this.column;
  }

  public void setColumn(Long column) {
    this.column = column;
  }

  public String getSchema() {
    return this.schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public Boolean getPublic_() {
    return this.public_;
  }

  public void setPublic_(Boolean public_) {
    this.public_ = public_;
  }

  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getVer() {
    return this.ver;
  }

  public void setVer(String ver) {
    this.ver = ver;
  }

  public Boolean getActive() {
    return this.active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public List<Items> getItems() {
    return this.items;
  }

  public void setItems(List<Items> items) {
    this.items = items;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Items extends Entity {
    private String type;

    private String name;

    private String title;

    private String description;

    private Object defaults;

    private Boolean disabled;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long row;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long col;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long rowSpan;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long colSpan;

    private String path;

    private List option;

    private String blockIcon;

    private String selectStyle;

    private String textPlaceholder;

    private String textIcon;

    private String textIconAppend;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long textRows;

    private String labelSize;

    private String labelColor;

    private Object validator;

    private String selectApi;

    private String selectApiUk;

    private String selectApiName;

    private Boolean selectMultiple;

    private String fileLimit;

    private String fileAccept;

    private Boolean allowTime;

    private String fileApi;

    private String fileUploadApi;

    private String fileTokenApi;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long scope;

    private Boolean fileMultiple;

    private Boolean lock;

    private Boolean isGroup;

    public String getType() {
      return this.type;
    }

    public void setType(String type) {
      this.type = type;
    }

    public String getName() {
      return this.name;
    }

    public void setName(String name) {
      this.name = name;
    }

    public String getTitle() {
      return this.title;
    }

    public void setTitle(String title) {
      this.title = title;
    }

    public String getDescription() {
      return this.description;
    }

    public void setDescription(String description) {
      this.description = description;
    }

    public Object getDefaults() {
      return this.defaults;
    }

    public void setDefaults(Object defaults) {
      this.defaults = defaults;
    }

    public Boolean getDisabled() {
      return this.disabled;
    }

    public void setDisabled(Boolean disabled) {
      this.disabled = disabled;
    }

    public Long getRow() {
      return this.row;
    }

    public void setRow(Long row) {
      this.row = row;
    }

    public Long getCol() {
      return this.col;
    }

    public void setCol(Long col) {
      this.col = col;
    }

    public Long getRowSpan() {
      return this.rowSpan;
    }

    public void setRowSpan(Long rowSpan) {
      this.rowSpan = rowSpan;
    }

    public Long getColSpan() {
      return this.colSpan;
    }

    public void setColSpan(Long colSpan) {
      this.colSpan = colSpan;
    }

    public String getPath() {
      return this.path;
    }

    public void setPath(String path) {
      this.path = path;
    }

    public List getOption() {
      return this.option;
    }

    public void setOption(List option) {
      this.option = option;
    }

    public String getBlockIcon() {
      return this.blockIcon;
    }

    public void setBlockIcon(String blockIcon) {
      this.blockIcon = blockIcon;
    }

    public String getSelectStyle() {
      return this.selectStyle;
    }

    public void setSelectStyle(String selectStyle) {
      this.selectStyle = selectStyle;
    }

    public String getTextPlaceholder() {
      return this.textPlaceholder;
    }

    public void setTextPlaceholder(String textPlaceholder) {
      this.textPlaceholder = textPlaceholder;
    }

    public String getTextIcon() {
      return this.textIcon;
    }

    public void setTextIcon(String textIcon) {
      this.textIcon = textIcon;
    }

    public String getTextIconAppend() {
      return this.textIconAppend;
    }

    public void setTextIconAppend(String textIconAppend) {
      this.textIconAppend = textIconAppend;
    }

    public Long getTextRows() {
      return this.textRows;
    }

    public void setTextRows(Long textRows) {
      this.textRows = textRows;
    }

    public String getLabelSize() {
      return this.labelSize;
    }

    public void setLabelSize(String labelSize) {
      this.labelSize = labelSize;
    }

    public String getLabelColor() {
      return this.labelColor;
    }

    public void setLabelColor(String labelColor) {
      this.labelColor = labelColor;
    }

    public Object getValidator() {
      return this.validator;
    }

    public void setValidator(Object validator) {
      this.validator = validator;
    }

    public String getSelectApi() {
      return this.selectApi;
    }

    public void setSelectApi(String selectApi) {
      this.selectApi = selectApi;
    }

    public String getSelectApiUk() {
      return this.selectApiUk;
    }

    public void setSelectApiUk(String selectApiUk) {
      this.selectApiUk = selectApiUk;
    }

    public String getSelectApiName() {
      return this.selectApiName;
    }

    public void setSelectApiName(String selectApiName) {
      this.selectApiName = selectApiName;
    }

    public Boolean getSelectMultiple() {
      return this.selectMultiple;
    }

    public void setSelectMultiple(Boolean selectMultiple) {
      this.selectMultiple = selectMultiple;
    }

    public String getFileLimit() {
      return this.fileLimit;
    }

    public void setFileLimit(String fileLimit) {
      this.fileLimit = fileLimit;
    }

    public String getFileAccept() {
      return this.fileAccept;
    }

    public void setFileAccept(String fileAccept) {
      this.fileAccept = fileAccept;
    }

    public Boolean getAllowTime() {
      return this.allowTime;
    }

    public void setAllowTime(Boolean allowTime) {
      this.allowTime = allowTime;
    }

    public String getFileApi() {
      return this.fileApi;
    }

    public void setFileApi(String fileApi) {
      this.fileApi = fileApi;
    }

    public String getFileUploadApi() {
      return this.fileUploadApi;
    }

    public void setFileUploadApi(String fileUploadApi) {
      this.fileUploadApi = fileUploadApi;
    }

    public String getFileTokenApi() {
      return this.fileTokenApi;
    }

    public void setFileTokenApi(String fileTokenApi) {
      this.fileTokenApi = fileTokenApi;
    }

    public Long getScope() {
      return this.scope;
    }

    public void setScope(Long scope) {
      this.scope = scope;
    }

    public Boolean getFileMultiple() {
      return this.fileMultiple;
    }

    public void setFileMultiple(Boolean fileMultiple) {
      this.fileMultiple = fileMultiple;
    }

    public Boolean getLock() {
      return this.lock;
    }

    public void setLock(Boolean lock) {
      this.lock = lock;
    }

    public Boolean getIsGroup() {
      return this.isGroup;
    }

    public void setIsGroup(Boolean isGroup) {
      this.isGroup = isGroup;
    }
  }
}
