package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;

import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModGroup extends ModCommon {
  private String outer;

  private List owners;

  private String type;

  private String visible;

  private String name;

  private List roles;

  private String description;

  private Object extend;

  private String parent;

  private String sort;

  private String status;

  public String getOuter() {
    return this.outer;
  }

  public void setOuter(String outer) {
    this.outer = outer;
  }

  public List getOwners() {
    return this.owners;
  }

  public void setOwners(List owners) {
    this.owners = owners;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getVisible() {
    return this.visible;
  }

  public void setVisible(String visible) {
    this.visible = visible;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public List getRoles() {
    return this.roles;
  }

  public void setRoles(List roles) {
    this.roles = roles;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Object getExtend() {
    return this.extend;
  }

  public void setExtend(Object extend) {
    this.extend = extend;
  }

  public String getParent() {
    return this.parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }

  public String getSort() {
    return this.sort;
  }

  public void setSort(String sort) {
    this.sort = sort;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }
}
