package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModBase;
import java.lang.Object;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModI18n extends ModBase {
  private String key;

  private Object lang;

  private String type;

  public String getKey() {
    return this.key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Object getLang() {
    return this.lang;
  }

  public void setLang(Object lang) {
    this.lang = lang;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }
}
