package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModI18n extends ModCommon {
  private String key;

  private Object lang;

  private String type;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long kind;

  private String version;

  public String getKey() {
    return this.key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Object getLang() {
    return this.lang;
  }

  public void setLang(Object lang) {
    this.lang = lang;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Long getKind() {
    return this.kind;
  }

  public void setKind(Long kind) {
    this.kind = kind;
  }

  public String getVersion() {
    return this.version;
  }

  public void setVersion(String version) {
    this.version = version;
  }
}
