package cn.alphabets.light.entity;

import cn.alphabets.light.model.Entity;
import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.DateDeserializer;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import cn.alphabets.light.model.serializer.DateSerializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;
import java.util.Date;
import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModJob extends ModCommon {
  private String name;

  private String run;

  private String schedule;

  @JsonDeserialize(
      using = DateDeserializer.class
  )
  @JsonSerialize(
      using = DateSerializer.class
  )
  private Date limit;

  private String status;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long count;

  @JsonDeserialize(
      using = DateDeserializer.class
  )
  @JsonSerialize(
      using = DateSerializer.class
  )
  private Date last;

  @JsonDeserialize(
      using = DateDeserializer.class
  )
  @JsonSerialize(
      using = DateSerializer.class
  )
  private Date start;

  private String description;

  private Object extend;

  private List<Step> step;

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getRun() {
    return this.run;
  }

  public void setRun(String run) {
    this.run = run;
  }

  public String getSchedule() {
    return this.schedule;
  }

  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }

  public Date getLimit() {
    return this.limit;
  }

  public void setLimit(Date limit) {
    this.limit = limit;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Long getCount() {
    return this.count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public Date getLast() {
    return this.last;
  }

  public void setLast(Date last) {
    this.last = last;
  }

  public Date getStart() {
    return this.start;
  }

  public void setStart(Date start) {
    this.start = start;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Object getExtend() {
    return this.extend;
  }

  public void setExtend(Object extend) {
    this.extend = extend;
  }

  public List<Step> getStep() {
    return this.step;
  }

  public void setStep(List<Step> step) {
    this.step = step;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Step extends Entity {
    private String script;

    private String type;

    private String action;

    @JsonProperty("class")
    private String class_;

    @JsonDeserialize(
        using = LongDeserializer.class
    )
    private Long index;

    private Object params;

    public String getScript() {
      return this.script;
    }

    public void setScript(String script) {
      this.script = script;
    }

    public String getType() {
      return this.type;
    }

    public void setType(String type) {
      this.type = type;
    }

    public String getAction() {
      return this.action;
    }

    public void setAction(String action) {
      this.action = action;
    }

    public String getClass_() {
      return this.class_;
    }

    public void setClass_(String class_) {
      this.class_ = class_;
    }

    public Long getIndex() {
      return this.index;
    }

    public void setIndex(Long index) {
      this.index = index;
    }

    public Object getParams() {
      return this.params;
    }

    public void setParams(Object params) {
      this.params = params;
    }
  }
}
