package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;
import java.lang.Object;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModLog extends ModCommon {
  private String transaction;

  private Object content;

  public String getTransaction() {
    return this.transaction;
  }

  public void setTransaction(String transaction) {
    this.transaction = transaction;
  }

  public Object getContent() {
    return this.content;
  }

  public void setContent(Object content) {
    this.content = content;
  }
}
