package cn.alphabets.light.entity;

import cn.alphabets.light.model.Entity;
import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModMarkdown extends ModCommon {
  private String body;

  private Option option;

  private String title;

  private String html;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long type;

  private String parent;

  public String getBody() {
    return this.body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public Option getOption() {
    return this.option;
  }

  public void setOption(Option option) {
    this.option = option;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getHtml() {
    return this.html;
  }

  public void setHtml(String html) {
    this.html = html;
  }

  public Long getType() {
    return this.type;
  }

  public void setType(Long type) {
    this.type = type;
  }

  public String getParent() {
    return this.parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Option extends Entity {
    private Boolean breaks;

    private Boolean html;

    private String linkify;

    public Boolean getBreaks() {
      return this.breaks;
    }

    public void setBreaks(Boolean breaks) {
      this.breaks = breaks;
    }

    public Boolean getHtml() {
      return this.html;
    }

    public void setHtml(Boolean html) {
      this.html = html;
    }

    public String getLinkify() {
      return this.linkify;
    }

    public void setLinkify(String linkify) {
      this.linkify = linkify;
    }
  }
}
