package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModCommon;
import java.lang.String;
import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModTenant extends ModCommon {
  private String description;

  private String logo;

  private String name;

  private String code;

  private List schema;

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getLogo() {
    return this.logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getCode() {
    return this.code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public List getSchema() {
    return this.schema;
  }

  public void setSchema(List schema) {
    this.schema = schema;
  }
}
