package cn.alphabets.light.entity;

import cn.alphabets.light.model.Entity;
import cn.alphabets.light.model.ModCommon;
import cn.alphabets.light.model.deserializer.LongDeserializer;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class ModValidator extends ModCommon {
  @JsonProperty("class")
  private String class_;

  private String message;

  private String name;

  private String action;

  private Condition condition;

  private String group;

  private String description;

  private String key;

  private String sanitize;

  private Object option;

  private String rule;

  private Boolean strict;

  @JsonDeserialize(
      using = LongDeserializer.class
  )
  private Long kind;

  private String version;

  public String getClass_() {
    return this.class_;
  }

  public void setClass_(String class_) {
    this.class_ = class_;
  }

  public String getMessage() {
    return this.message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getAction() {
    return this.action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public Condition getCondition() {
    return this.condition;
  }

  public void setCondition(Condition condition) {
    this.condition = condition;
  }

  public String getGroup() {
    return this.group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getKey() {
    return this.key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public String getSanitize() {
    return this.sanitize;
  }

  public void setSanitize(String sanitize) {
    this.sanitize = sanitize;
  }

  public Object getOption() {
    return this.option;
  }

  public void setOption(Object option) {
    this.option = option;
  }

  public String getRule() {
    return this.rule;
  }

  public void setRule(String rule) {
    this.rule = rule;
  }

  public Boolean getStrict() {
    return this.strict;
  }

  public void setStrict(Boolean strict) {
    this.strict = strict;
  }

  public Long getKind() {
    return this.kind;
  }

  public void setKind(Long kind) {
    this.kind = kind;
  }

  public String getVersion() {
    return this.version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Condition extends Entity {
    private String operator;

    private String parameter;

    private String key;

    public String getOperator() {
      return this.operator;
    }

    public void setOperator(String operator) {
      this.operator = operator;
    }

    public String getParameter() {
      return this.parameter;
    }

    public void setParameter(String parameter) {
      this.parameter = parameter;
    }

    public String getKey() {
      return this.key;
    }

    public void setKey(String key) {
      this.key = key;
    }
  }
}
