package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModBase;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Long;
import java.lang.Object;
import java.lang.String;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class Structure extends ModBase {
  private String description;

  private Long lock;

  private String schema;

  private Long tenant;

  private String version;

  private Object extend;

  private Object items;

  private Long kind;

  @JsonProperty("public")
  private Long public_;

  private Long type;

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Long getLock() {
    return this.lock;
  }

  public void setLock(Long lock) {
    this.lock = lock;
  }

  public String getSchema() {
    return this.schema;
  }

  public void setSchema(String schema) {
    this.schema = schema;
  }

  public Long getTenant() {
    return this.tenant;
  }

  public void setTenant(Long tenant) {
    this.tenant = tenant;
  }

  public String getVersion() {
    return this.version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public Object getExtend() {
    return this.extend;
  }

  public void setExtend(Object extend) {
    this.extend = extend;
  }

  public Object getItems() {
    return this.items;
  }

  public void setItems(Object items) {
    this.items = items;
  }

  public Long getKind() {
    return this.kind;
  }

  public void setKind(Long kind) {
    this.kind = kind;
  }

  public Long getPublic_() {
    return this.public_;
  }

  public void setPublic_(Long public_) {
    this.public_ = public_;
  }

  public Long getType() {
    return this.type;
  }

  public void setType(Long type) {
    this.type = type;
  }
}
