package cn.alphabets.light.entity;

import cn.alphabets.light.model.ModBase;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Object;
import java.lang.String;
import java.util.List;

/**
 * Generated by the Light platform. Do not manually modify the code.
 */
public class Validator extends ModBase {
  @JsonProperty("class")
  private String class_;

  private String message;

  private String name;

  private String action;

  private Object condition;

  private String group;

  private String description;

  private String key;

  private String sanitize;

  private List option;

  private String rule;

  public String getClass_() {
    return this.class_;
  }

  public void setClass_(String class_) {
    this.class_ = class_;
  }

  public String getMessage() {
    return this.message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getAction() {
    return this.action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public Object getCondition() {
    return this.condition;
  }

  public void setCondition(Object condition) {
    this.condition = condition;
  }

  public String getGroup() {
    return this.group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getKey() {
    return this.key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public String getSanitize() {
    return this.sanitize;
  }

  public void setSanitize(String sanitize) {
    this.sanitize = sanitize;
  }

  public List getOption() {
    return this.option;
  }

  public void setOption(List option) {
    this.option = option;
  }

  public String getRule() {
    return this.rule;
  }

  public void setRule(String rule) {
    this.rule = rule;
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Condition {
    private String operator;

    private String parameter;

    private String value;

    public String getOperator() {
      return this.operator;
    }

    public void setOperator(String operator) {
      this.operator = operator;
    }

    public String getParameter() {
      return this.parameter;
    }

    public void setParameter(String parameter) {
      this.parameter = parameter;
    }

    public String getValue() {
      return this.value;
    }

    public void setValue(String value) {
      this.value = value;
    }
  }
}
