package cn.alphabets.light;

import cn.alphabets.light.model.Json;
import org.apache.commons.lang3.math.NumberUtils;
import org.jtwig.JtwigModel;
import org.jtwig.JtwigTemplate;
import org.jtwig.environment.Environment;
import org.jtwig.environment.EnvironmentConfiguration;
import org.jtwig.environment.EnvironmentConfigurationBuilder;
import org.jtwig.environment.EnvironmentFactory;
import org.jtwig.functions.FunctionRequest;
import org.jtwig.functions.SimpleJtwigFunction;
import org.jtwig.resource.reference.ResourceReference;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Helper
 */
public class Helper {

    /**
     * An singleton instance of the template engine
     */
    private static JtwigTemplate template;


    /**
     * Use Json Path to set the value of the Json object. Supports embedded objects
     *
     * @param source target json object
     * @param path   json path
     * @param val    value
     */
    @SuppressWarnings("unchecked")
    public static void setValueByJsonPath(Json source, List<String> path, Object val) {

        Object parent = source;

        for (int i = 0; i < path.size(); i++) {

            String key = path.get(i);
            boolean isLast = (i == path.size() - 1);

            if (isLast) {
                boolean isList = key.equals("") || NumberUtils.isDigits(key);
                if (isList) {
                    ((List<Object>) parent).add(val);
                } else {
                    ((Json) parent).put(key, val);
                }
                return;
            }

            boolean isListValue = path.get(i + 1).equals("") || NumberUtils.isDigits(path.get(i + 1));
            boolean isObjectValue = !isListValue;

            if (NumberUtils.isDigits(key)) {

                if (((List<?>) parent).size() > Integer.parseInt(key)) {
                    parent = ((List<?>) parent).get(Integer.parseInt(key));
                } else {
                    if (isListValue) {
                        ((List<Object>) parent).add(new ArrayList<>());
                    }
                    if (isObjectValue) {
                        ((List<Json>) parent).add(new Json());
                    }
                    parent = ((List<?>) parent).get(Integer.parseInt(key));
                }
            } else {

                if (((Json) parent).containsKey(key)) {
                    parent = ((Json) parent).get(key);
                } else {
                    if (isListValue) {
                        ((Json) parent).put(key, new ArrayList<>());
                    }
                    if (isObjectValue) {
                        ((Json) parent).put(key, new Json());
                    }
                    parent = ((Json) parent).get(key);
                }
            }
        }
    }

    /**
     * Deserializes the JSON generated by JQuery.param() method
     *
     * @param url full request url
     * @return Json Object
     */
    public static Json unParam(String url) {

        String decoded;
        Pattern pattern = Pattern.compile("\\[([^\\]]*)\\]");

        try {
            url = url.contains("?") ? url.substring(url.indexOf("?") + 1) : url;
            decoded = URLDecoder.decode(url, "UTF-8");
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }

        final Json json = new Json();

        Arrays.stream(decoded.split("&")).forEach(keyVal -> {

            String[] splitted = keyVal.split("=");
            String key = splitted[0];
            String val = splitted.length > 1 ? splitted[1] : "";

            List<String> path = new ArrayList<>();
            path.add(key.indexOf("[") > 0 ? key.substring(0, key.indexOf("[")) : key);

            Matcher m = pattern.matcher(key);
            while (m.find()) {
                path.add(m.group(1));
            }

            Helper.setValueByJsonPath(json, path, val);
        });

        return json;
    }

    /**
     * Use the template file to generate a string
     *
     * @param name     resource name
     * @param model    parameters
     * @param function custom functions
     * @return The resulting string
     */
    public static String loadTemplate(String name, Map<String, Object> model, List<TemplateFunction> function) {

        if (template == null) {
            EnvironmentConfiguration configuration = EnvironmentConfigurationBuilder
                    .configuration()
                    .functions()
                    .add(function)
                    .and()
                    .parser()
                    .syntax()
                    .withStartCode("<%~").withEndCode("%>")
                    .withStartOutput("<%=").withEndOutput("%>")
                    .withStartComment("<#").withEndComment("#>")
                    .and()
                    .and()
                    .build();

            Environment environment = new EnvironmentFactory().create(configuration);
            ResourceReference resource = new ResourceReference(ResourceReference.CLASSPATH, name);

            template = new JtwigTemplate(environment, resource);
        }
        return template.render(JtwigModel.newModel(model));
    }

    static void cleanTemplate() {
        template = null;
    }

    public static class TemplateFunction extends SimpleJtwigFunction {

        private String name;
        Function<List<Object>, String> function;

        public TemplateFunction(String name, Function<List<Object>, String> function) {
            this.name = name;
            this.function = function;
        }

        @Override
        public String name() {
            return this.name;
        }

        @Override
        public Object execute(FunctionRequest request) {
            return this.function.apply(request.getArguments());
        }
    }
}
